// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { auditListAuditEventsData, auditListAuditEventsErrors, auditListAuditEventsResponses, contactsListContactsData, contactsListContactsErrors, contactsListContactsResponses, dashboardDashboardData, dashboardDashboardResponses, importsCancelImportData, importsCancelImportErrors, importsCancelImportResponses, importsConfirmImportData, importsConfirmImportErrors, importsConfirmImportResponses, importsDownloadReportData, importsDownloadReportErrors, importsDownloadReportResponses, importsGetImportData, importsGetImportErrors, importsGetImportResponses, importsListImportsData, importsListImportsErrors, importsListImportsResponses, importsListValidationRowsData, importsListValidationRowsErrors, importsListValidationRowsResponses, importsRetryImportData, importsRetryImportErrors, importsRetryImportResponses, importsSetMappingData, importsSetMappingErrors, importsSetMappingResponses, importsUploadImportData, importsUploadImportErrors, importsUploadImportResponses, importsValidateImportData, importsValidateImportErrors, importsValidateImportResponses, jobsGetJobData, jobsGetJobErrors, jobsGetJobResponses, jobsListAttemptsData, jobsListAttemptsErrors, jobsListAttemptsResponses, loginLoginAccessTokenData, loginLoginAccessTokenErrors, loginLoginAccessTokenResponses, operationsLivenessData, operationsLivenessResponses, operationsReadinessData, operationsReadinessResponses, operationsVersionData, operationsVersionResponses, usersChangePasswordData, usersChangePasswordErrors, usersChangePasswordResponses, usersCreateUserData, usersCreateUserErrors, usersCreateUserResponses, usersIssueTemporaryPasswordData, usersIssueTemporaryPasswordErrors, usersIssueTemporaryPasswordResponses, usersListUsersData, usersListUsersErrors, usersListUsersResponses, usersReadUserData, usersReadUserErrors, usersReadUserMeData, usersReadUserMeResponses, usersReadUserResponses, usersUpdateUserData, usersUpdateUserErrors, usersUpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class LoginService {
    /**
     * Login Access Token
     */
    public static loginAccessToken<ThrowOnError extends boolean = true>(options: Options<loginLoginAccessTokenData, ThrowOnError>) {
        return (options.client ?? client).post<loginLoginAccessTokenResponses, loginLoginAccessTokenErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/v1/login/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }
}

export class UsersService {
    /**
     * List Users
     */
    public static listUsers<ThrowOnError extends boolean = true>(options?: Options<usersListUsersData, ThrowOnError>) {
        return (options?.client ?? client).get<usersListUsersResponses, usersListUsersErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users',
            ...options
        });
    }
    
    /**
     * Create User
     */
    public static createUser<ThrowOnError extends boolean = true>(options: Options<usersCreateUserData, ThrowOnError>) {
        return (options.client ?? client).post<usersCreateUserResponses, usersCreateUserErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Read User Me
     */
    public static readUserMe<ThrowOnError extends boolean = true>(options?: Options<usersReadUserMeData, ThrowOnError>) {
        return (options?.client ?? client).get<usersReadUserMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Change Password
     */
    public static changePassword<ThrowOnError extends boolean = true>(options: Options<usersChangePasswordData, ThrowOnError>) {
        return (options.client ?? client).post<usersChangePasswordResponses, usersChangePasswordErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me/password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Read User
     */
    public static readUser<ThrowOnError extends boolean = true>(options: Options<usersReadUserData, ThrowOnError>) {
        return (options.client ?? client).get<usersReadUserResponses, usersReadUserErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Update User
     */
    public static updateUser<ThrowOnError extends boolean = true>(options: Options<usersUpdateUserData, ThrowOnError>) {
        return (options.client ?? client).patch<usersUpdateUserResponses, usersUpdateUserErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/{user_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Issue Temporary Password
     */
    public static issueTemporaryPassword<ThrowOnError extends boolean = true>(options: Options<usersIssueTemporaryPasswordData, ThrowOnError>) {
        return (options.client ?? client).post<usersIssueTemporaryPasswordResponses, usersIssueTemporaryPasswordErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/{user_id}/temporary-password',
            ...options
        });
    }
}

export class DashboardService {
    /**
     * Dashboard
     */
    public static dashboard<ThrowOnError extends boolean = true>(options?: Options<dashboardDashboardData, ThrowOnError>) {
        return (options?.client ?? client).get<dashboardDashboardResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/dashboard',
            ...options
        });
    }
}

export class ImportsService {
    /**
     * List Imports
     */
    public static listImports<ThrowOnError extends boolean = true>(options?: Options<importsListImportsData, ThrowOnError>) {
        return (options?.client ?? client).get<importsListImportsResponses, importsListImportsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/imports',
            ...options
        });
    }
    
    /**
     * Upload Import
     */
    public static uploadImport<ThrowOnError extends boolean = true>(options: Options<importsUploadImportData, ThrowOnError>) {
        return (options.client ?? client).post<importsUploadImportResponses, importsUploadImportErrors, ThrowOnError>({
            ...formDataBodySerializer,
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/imports',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    /**
     * Get Import
     */
    public static getImport<ThrowOnError extends boolean = true>(options: Options<importsGetImportData, ThrowOnError>) {
        return (options.client ?? client).get<importsGetImportResponses, importsGetImportErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/imports/{import_id}',
            ...options
        });
    }
    
    /**
     * Set Mapping
     */
    public static setMapping<ThrowOnError extends boolean = true>(options: Options<importsSetMappingData, ThrowOnError>) {
        return (options.client ?? client).put<importsSetMappingResponses, importsSetMappingErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/imports/{import_id}/mapping',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Validate Import
     */
    public static validateImport<ThrowOnError extends boolean = true>(options: Options<importsValidateImportData, ThrowOnError>) {
        return (options.client ?? client).post<importsValidateImportResponses, importsValidateImportErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/imports/{import_id}/validate',
            ...options
        });
    }
    
    /**
     * Confirm Import
     */
    public static confirmImport<ThrowOnError extends boolean = true>(options: Options<importsConfirmImportData, ThrowOnError>) {
        return (options.client ?? client).post<importsConfirmImportResponses, importsConfirmImportErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/imports/{import_id}/confirm',
            ...options
        });
    }
    
    /**
     * Cancel Import
     */
    public static cancelImport<ThrowOnError extends boolean = true>(options: Options<importsCancelImportData, ThrowOnError>) {
        return (options.client ?? client).post<importsCancelImportResponses, importsCancelImportErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/imports/{import_id}/cancel',
            ...options
        });
    }
    
    /**
     * Retry Import
     */
    public static retryImport<ThrowOnError extends boolean = true>(options: Options<importsRetryImportData, ThrowOnError>) {
        return (options.client ?? client).post<importsRetryImportResponses, importsRetryImportErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/imports/{import_id}/retry',
            ...options
        });
    }
    
    /**
     * List Validation Rows
     */
    public static listValidationRows<ThrowOnError extends boolean = true>(options: Options<importsListValidationRowsData, ThrowOnError>) {
        return (options.client ?? client).get<importsListValidationRowsResponses, importsListValidationRowsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/imports/{import_id}/rows',
            ...options
        });
    }
    
    /**
     * Download Report
     */
    public static downloadReport<ThrowOnError extends boolean = true>(options: Options<importsDownloadReportData, ThrowOnError>) {
        return (options.client ?? client).get<importsDownloadReportResponses, importsDownloadReportErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/imports/{import_id}/reports/{report_name}',
            ...options
        });
    }
}

export class JobsService {
    /**
     * Get Job
     */
    public static getJob<ThrowOnError extends boolean = true>(options: Options<jobsGetJobData, ThrowOnError>) {
        return (options.client ?? client).get<jobsGetJobResponses, jobsGetJobErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/jobs/{job_id}',
            ...options
        });
    }
    
    /**
     * List Attempts
     */
    public static listAttempts<ThrowOnError extends boolean = true>(options: Options<jobsListAttemptsData, ThrowOnError>) {
        return (options.client ?? client).get<jobsListAttemptsResponses, jobsListAttemptsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/jobs/{job_id}/attempts',
            ...options
        });
    }
}

export class ContactsService {
    /**
     * List Contacts
     */
    public static listContacts<ThrowOnError extends boolean = true>(options?: Options<contactsListContactsData, ThrowOnError>) {
        return (options?.client ?? client).get<contactsListContactsResponses, contactsListContactsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/contacts',
            ...options
        });
    }
}

export class AuditService {
    /**
     * List Audit Events
     */
    public static listAuditEvents<ThrowOnError extends boolean = true>(options?: Options<auditListAuditEventsData, ThrowOnError>) {
        return (options?.client ?? client).get<auditListAuditEventsResponses, auditListAuditEventsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/audit-events',
            ...options
        });
    }
}

export class OperationsService {
    /**
     * Liveness
     */
    public static liveness<ThrowOnError extends boolean = true>(options?: Options<operationsLivenessData, ThrowOnError>) {
        return (options?.client ?? client).get<operationsLivenessResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/health/live',
            ...options
        });
    }
    
    /**
     * Readiness
     */
    public static readiness<ThrowOnError extends boolean = true>(options?: Options<operationsReadinessData, ThrowOnError>) {
        return (options?.client ?? client).get<operationsReadinessResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/health/ready',
            ...options
        });
    }
    
    /**
     * Version
     */
    public static version<ThrowOnError extends boolean = true>(options?: Options<operationsVersionData, ThrowOnError>) {
        return (options?.client ?? client).get<operationsVersionResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/version',
            ...options
        });
    }
}
