// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AuditEventPage
 */
export type AuditEventPage = {
    /**
     * Data
     */
    data: Array<AuditEventPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
    /**
     * Has More
     */
    has_more: boolean;
};

/**
 * AuditEventPublic
 */
export type AuditEventPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Actor Id
     */
    actor_id: string | null;
    /**
     * Action
     */
    action: string;
    /**
     * Resource Type
     */
    resource_type: string;
    /**
     * Resource Id
     */
    resource_id: string | null;
    /**
     * Metadata Json
     */
    metadata_json: {
        [key: string]: unknown;
    };
    /**
     * Request Id
     */
    request_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * Body_imports-upload_import
 */
export type Body_imports_upload_import = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ContactPage
 */
export type ContactPage = {
    /**
     * Data
     */
    data: Array<ContactPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
    /**
     * Has More
     */
    has_more: boolean;
};

/**
 * ContactPublic
 */
export type ContactPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Company
     */
    company: string | null;
    /**
     * Country Code
     */
    country_code: string | null;
    /**
     * External Id
     */
    external_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DashboardPublic
 */
export type DashboardPublic = {
    /**
     * Imports Total
     */
    imports_total: number;
    /**
     * Contacts Total
     */
    contacts_total: number;
    /**
     * Accepted Rows Total
     */
    accepted_rows_total: number;
    /**
     * Rejected Rows Total
     */
    rejected_rows_total: number;
    /**
     * Duplicate Rows Total
     */
    duplicate_rows_total: number;
    /**
     * Jobs By Status
     */
    jobs_by_status: {
        [key: string]: number;
    };
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthPublic
 */
export type HealthPublic = {
    /**
     * Status
     */
    status: string;
};

/**
 * ImportAction
 */
export type ImportAction = {
    import_batch: ImportPublic;
    /**
     * Job Id
     */
    job_id?: string | null;
};

/**
 * ImportPage
 */
export type ImportPage = {
    /**
     * Data
     */
    data: Array<ImportPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
    /**
     * Has More
     */
    has_more: boolean;
};

/**
 * ImportPreview
 */
export type ImportPreview = {
    /**
     * Header
     */
    header: Array<string>;
    /**
     * Rows
     */
    rows: Array<Array<string>>;
    /**
     * Truncated
     */
    truncated: boolean;
};

/**
 * ImportPublic
 */
export type ImportPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Original Filename
     */
    original_filename: string;
    status: ImportStatus;
    /**
     * Mapping
     */
    mapping: {
        [key: string]: string;
    } | null;
    /**
     * Header
     */
    header: Array<string>;
    /**
     * Total Rows
     */
    total_rows: number;
    /**
     * Accepted Count
     */
    accepted_count: number;
    /**
     * Rejected Count
     */
    rejected_count: number;
    /**
     * Duplicate Count
     */
    duplicate_count: number;
    /**
     * Existing Contact Count
     */
    existing_contact_count: number;
    /**
     * Inserted Count
     */
    inserted_count: number;
    /**
     * Skipped Count
     */
    skipped_count: number;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created By Id
     */
    created_by_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ImportStatus
 */
export type ImportStatus = 'uploaded' | 'mapped' | 'validating' | 'validated' | 'importing' | 'completed' | 'failed' | 'cancelled';

/**
 * JobAttemptPage
 */
export type JobAttemptPage = {
    /**
     * Data
     */
    data: Array<JobAttemptPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
    /**
     * Has More
     */
    has_more: boolean;
};

/**
 * JobAttemptPublic
 */
export type JobAttemptPublic = {
    /**
     * Attempt Number
     */
    attempt_number: number;
    status: JobStatus;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * JobKind
 */
export type JobKind = 'validate' | 'confirm';

/**
 * JobPublic
 */
export type JobPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Import Id
     */
    import_id: string;
    kind: JobKind;
    status: JobStatus;
    /**
     * Attempt Count
     */
    attempt_count: number;
    /**
     * Max Attempts
     */
    max_attempts: number;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * JobStatus
 */
export type JobStatus = 'queued' | 'running' | 'succeeded' | 'failed' | 'cancel_requested' | 'cancelled';

/**
 * MappingUpdate
 */
export type MappingUpdate = {
    /**
     * Mapping
     */
    mapping: {
        [key: string]: string;
    };
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * PasswordChange
 */
export type PasswordChange = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * RowOutcome
 */
export type RowOutcome = 'accepted' | 'invalid' | 'file_duplicate' | 'existing_contact';

/**
 * TemporaryPassword
 */
export type TemporaryPassword = {
    /**
     * Temporary Password
     */
    temporary_password: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Must Change Password
     */
    must_change_password?: boolean;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
};

/**
 * UserCreated
 */
export type UserCreated = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Must Change Password
     */
    must_change_password: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Temporary Password
     */
    temporary_password: string;
};

/**
 * UserPage
 */
export type UserPage = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
    /**
     * Has More
     */
    has_more: boolean;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Must Change Password
     */
    must_change_password: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserRole
 */
export type UserRole = 'admin' | 'operator' | 'viewer';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ValidationRowPage
 */
export type ValidationRowPage = {
    /**
     * Data
     */
    data: Array<ValidationRowPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
    /**
     * Has More
     */
    has_more: boolean;
};

/**
 * ValidationRowPublic
 */
export type ValidationRowPublic = {
    /**
     * Row Number
     */
    row_number: number;
    outcome: RowOutcome;
    /**
     * Clean Data
     */
    clean_data: {
        [key: string]: string | null;
    } | null;
    /**
     * Errors
     */
    errors: Array<{
        [key: string]: string;
    }>;
};

/**
 * VersionPublic
 */
export type VersionPublic = {
    /**
     * Version
     */
    version: string;
    /**
     * Environment
     */
    environment: string;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type usersListUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users';
};

export type usersListUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersListUsersError = usersListUsersErrors[keyof usersListUsersErrors];

export type usersListUsersResponses = {
    /**
     * Successful Response
     */
    200: UserPage;
};

export type usersListUsersResponse = usersListUsersResponses[keyof usersListUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserCreated;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersChangePasswordData = {
    body: PasswordChange;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersChangePasswordError = usersChangePasswordErrors[keyof usersChangePasswordErrors];

export type usersChangePasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersChangePasswordResponse = usersChangePasswordResponses[keyof usersChangePasswordResponses];

export type usersReadUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserError = usersReadUserErrors[keyof usersReadUserErrors];

export type usersReadUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserResponse = usersReadUserResponses[keyof usersReadUserResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type usersIssueTemporaryPasswordData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/temporary-password';
};

export type usersIssueTemporaryPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersIssueTemporaryPasswordError = usersIssueTemporaryPasswordErrors[keyof usersIssueTemporaryPasswordErrors];

export type usersIssueTemporaryPasswordResponses = {
    /**
     * Successful Response
     */
    200: TemporaryPassword;
};

export type usersIssueTemporaryPasswordResponse = usersIssueTemporaryPasswordResponses[keyof usersIssueTemporaryPasswordResponses];

export type dashboardDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard';
};

export type dashboardDashboardResponses = {
    /**
     * Successful Response
     */
    200: DashboardPublic;
};

export type dashboardDashboardResponse = dashboardDashboardResponses[keyof dashboardDashboardResponses];

export type importsListImportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/imports';
};

export type importsListImportsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsListImportsError = importsListImportsErrors[keyof importsListImportsErrors];

export type importsListImportsResponses = {
    /**
     * Successful Response
     */
    200: ImportPage;
};

export type importsListImportsResponse = importsListImportsResponses[keyof importsListImportsResponses];

export type importsUploadImportData = {
    body: Body_imports_upload_import;
    path?: never;
    query?: never;
    url: '/api/v1/imports';
};

export type importsUploadImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsUploadImportError = importsUploadImportErrors[keyof importsUploadImportErrors];

export type importsUploadImportResponses = {
    /**
     * Successful Response
     */
    201: ImportPublic;
};

export type importsUploadImportResponse = importsUploadImportResponses[keyof importsUploadImportResponses];

export type importsGetImportData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}';
};

export type importsGetImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsGetImportError = importsGetImportErrors[keyof importsGetImportErrors];

export type importsGetImportResponses = {
    /**
     * Successful Response
     */
    200: ImportPublic;
};

export type importsGetImportResponse = importsGetImportResponses[keyof importsGetImportResponses];

export type importsPreviewImportData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}/preview';
};

export type importsPreviewImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsPreviewImportError = importsPreviewImportErrors[keyof importsPreviewImportErrors];

export type importsPreviewImportResponses = {
    /**
     * Successful Response
     */
    200: ImportPreview;
};

export type importsPreviewImportResponse = importsPreviewImportResponses[keyof importsPreviewImportResponses];

export type importsSetMappingData = {
    body: MappingUpdate;
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}/mapping';
};

export type importsSetMappingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsSetMappingError = importsSetMappingErrors[keyof importsSetMappingErrors];

export type importsSetMappingResponses = {
    /**
     * Successful Response
     */
    200: ImportPublic;
};

export type importsSetMappingResponse = importsSetMappingResponses[keyof importsSetMappingResponses];

export type importsValidateImportData = {
    body?: never;
    headers?: {
        /**
         * Traceparent
         */
        traceparent?: string | null;
    };
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}/validate';
};

export type importsValidateImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsValidateImportError = importsValidateImportErrors[keyof importsValidateImportErrors];

export type importsValidateImportResponses = {
    /**
     * Successful Response
     */
    202: ImportAction;
};

export type importsValidateImportResponse = importsValidateImportResponses[keyof importsValidateImportResponses];

export type importsConfirmImportData = {
    body?: never;
    headers: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key': string;
        /**
         * Traceparent
         */
        traceparent?: string | null;
    };
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}/confirm';
};

export type importsConfirmImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsConfirmImportError = importsConfirmImportErrors[keyof importsConfirmImportErrors];

export type importsConfirmImportResponses = {
    /**
     * Successful Response
     */
    202: ImportAction;
};

export type importsConfirmImportResponse = importsConfirmImportResponses[keyof importsConfirmImportResponses];

export type importsCancelImportData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}/cancel';
};

export type importsCancelImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsCancelImportError = importsCancelImportErrors[keyof importsCancelImportErrors];

export type importsCancelImportResponses = {
    /**
     * Successful Response
     */
    200: ImportAction;
};

export type importsCancelImportResponse = importsCancelImportResponses[keyof importsCancelImportResponses];

export type importsRetryImportData = {
    body?: never;
    headers?: {
        /**
         * Traceparent
         */
        traceparent?: string | null;
    };
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}/retry';
};

export type importsRetryImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsRetryImportError = importsRetryImportErrors[keyof importsRetryImportErrors];

export type importsRetryImportResponses = {
    /**
     * Successful Response
     */
    202: ImportAction;
};

export type importsRetryImportResponse = importsRetryImportResponses[keyof importsRetryImportResponses];

export type importsListValidationRowsData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: {
        /**
         * Outcome
         */
        outcome?: RowOutcome | null;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/imports/{import_id}/rows';
};

export type importsListValidationRowsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsListValidationRowsError = importsListValidationRowsErrors[keyof importsListValidationRowsErrors];

export type importsListValidationRowsResponses = {
    /**
     * Successful Response
     */
    200: ValidationRowPage;
};

export type importsListValidationRowsResponse = importsListValidationRowsResponses[keyof importsListValidationRowsResponses];

export type importsDownloadReportData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: string;
        /**
         * Report Name
         */
        report_name: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}/reports/{report_name}';
};

export type importsDownloadReportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsDownloadReportError = importsDownloadReportErrors[keyof importsDownloadReportErrors];

export type importsDownloadReportResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type jobsGetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}';
};

export type jobsGetJobErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type jobsGetJobError = jobsGetJobErrors[keyof jobsGetJobErrors];

export type jobsGetJobResponses = {
    /**
     * Successful Response
     */
    200: JobPublic;
};

export type jobsGetJobResponse = jobsGetJobResponses[keyof jobsGetJobResponses];

export type jobsListAttemptsData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/jobs/{job_id}/attempts';
};

export type jobsListAttemptsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type jobsListAttemptsError = jobsListAttemptsErrors[keyof jobsListAttemptsErrors];

export type jobsListAttemptsResponses = {
    /**
     * Successful Response
     */
    200: JobAttemptPage;
};

export type jobsListAttemptsResponse = jobsListAttemptsResponses[keyof jobsListAttemptsResponses];

export type contactsListContactsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/contacts';
};

export type contactsListContactsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type contactsListContactsError = contactsListContactsErrors[keyof contactsListContactsErrors];

export type contactsListContactsResponses = {
    /**
     * Successful Response
     */
    200: ContactPage;
};

export type contactsListContactsResponse = contactsListContactsResponses[keyof contactsListContactsResponses];

export type auditListAuditEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Action
         */
        action?: string | null;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/audit-events';
};

export type auditListAuditEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type auditListAuditEventsError = auditListAuditEventsErrors[keyof auditListAuditEventsErrors];

export type auditListAuditEventsResponses = {
    /**
     * Successful Response
     */
    200: AuditEventPage;
};

export type auditListAuditEventsResponse = auditListAuditEventsResponses[keyof auditListAuditEventsResponses];

export type operationsLivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live';
};

export type operationsLivenessResponses = {
    /**
     * Successful Response
     */
    200: HealthPublic;
};

export type operationsLivenessResponse = operationsLivenessResponses[keyof operationsLivenessResponses];

export type operationsReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type operationsReadinessResponses = {
    /**
     * Successful Response
     */
    200: HealthPublic;
};

export type operationsReadinessResponse = operationsReadinessResponses[keyof operationsReadinessResponses];

export type operationsVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/version';
};

export type operationsVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionPublic;
};

export type operationsVersionResponse = operationsVersionResponses[keyof operationsVersionResponses];
