apiVersion: v1
kind: Service
metadata:
  name: {{ include "fde.fullname" . }}-api
  labels:
    {{- include "fde.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: api }
  ports:
    - { name: http, port: 8000, targetPort: http }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fde.fullname" . }}-metrics
  labels:
    {{- include "fde.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: api }
  ports:
    - { name: metrics, port: 8000, targetPort: http }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fde.fullname" . }}-worker-metrics
  labels:
    {{- include "fde.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker-metrics
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: worker }
  ports:
    - { name: metrics, port: 9100, targetPort: metrics }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fde.fullname" . }}-frontend
  labels:
    {{- include "fde.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: frontend }
  ports:
    - { name: http, port: 8080, targetPort: http }
