customer: demo
environment: staging
project: fdetemplate
region: northamerica-northeast1
zone: northamerica-northeast1-a
profile: demo
namespace: staging
image_repository: northamerica-northeast1-docker.pkg.dev/fdetemplate/fde-demo-images/api
image_digest: sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
frontend_image_repository: northamerica-northeast1-docker.pkg.dev/fdetemplate/fde-demo-images/frontend
frontend_image_digest: sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
app_version: v1.0.0-demo
branding:
  name: FDE Demonstration Directory
sizing:
  api_replicas: 2
  worker_replicas: 1
  api_cpu: 250m
  api_memory: 384Mi
  worker_cpu: 250m
  worker_memory: 384Mi
