/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAuditRouteImport } from './routes/_layout/audit'
import { Route as LayoutDirectoryRouteImport } from './routes/_layout/directory'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutImportsIndexRouteImport } from './routes/_layout/imports/index'
import { Route as LayoutImportsImportIdRouteImport } from './routes/_layout/imports/$importId'
import { Route as LayoutImportsNewRouteImport } from './routes/_layout/imports/new'
import { Route as LayoutJobsIndexRouteImport } from './routes/_layout/jobs/index'
import { Route as LayoutJobsJobIdRouteImport } from './routes/_layout/jobs/$jobId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditRoute = LayoutAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDirectoryRoute = LayoutDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImportsIndexRoute = LayoutImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImportsImportIdRoute = LayoutImportsImportIdRouteImport.update({
  id: '/imports/$importId',
  path: '/imports/$importId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImportsNewRoute = LayoutImportsNewRouteImport.update({
  id: '/imports/new',
  path: '/imports/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJobsIndexRoute = LayoutJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJobsJobIdRoute = LayoutJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/audit': typeof LayoutAuditRoute
  '/directory': typeof LayoutDirectoryRoute
  '/settings': typeof LayoutSettingsRoute
  '/imports/$importId': typeof LayoutImportsImportIdRoute
  '/imports/new': typeof LayoutImportsNewRoute
  '/jobs/$jobId': typeof LayoutJobsJobIdRoute
  '/imports/': typeof LayoutImportsIndexRoute
  '/jobs/': typeof LayoutJobsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/audit': typeof LayoutAuditRoute
  '/directory': typeof LayoutDirectoryRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/imports/$importId': typeof LayoutImportsImportIdRoute
  '/imports/new': typeof LayoutImportsNewRoute
  '/jobs/$jobId': typeof LayoutJobsJobIdRoute
  '/imports': typeof LayoutImportsIndexRoute
  '/jobs': typeof LayoutJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/audit': typeof LayoutAuditRoute
  '/_layout/directory': typeof LayoutDirectoryRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/imports/$importId': typeof LayoutImportsImportIdRoute
  '/_layout/imports/new': typeof LayoutImportsNewRoute
  '/_layout/jobs/$jobId': typeof LayoutJobsJobIdRoute
  '/_layout/imports/': typeof LayoutImportsIndexRoute
  '/_layout/jobs/': typeof LayoutJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/audit'
    | '/directory'
    | '/settings'
    | '/imports/$importId'
    | '/imports/new'
    | '/jobs/$jobId'
    | '/imports/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/audit'
    | '/directory'
    | '/settings'
    | '/'
    | '/imports/$importId'
    | '/imports/new'
    | '/jobs/$jobId'
    | '/imports'
    | '/jobs'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/admin'
    | '/_layout/audit'
    | '/_layout/directory'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/imports/$importId'
    | '/_layout/imports/new'
    | '/_layout/jobs/$jobId'
    | '/_layout/imports/'
    | '/_layout/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit': {
      id: '/_layout/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof LayoutAuditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/directory': {
      id: '/_layout/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof LayoutDirectoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/imports/': {
      id: '/_layout/imports/'
      path: '/imports'
      fullPath: '/imports/'
      preLoaderRoute: typeof LayoutImportsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/imports/$importId': {
      id: '/_layout/imports/$importId'
      path: '/imports/$importId'
      fullPath: '/imports/$importId'
      preLoaderRoute: typeof LayoutImportsImportIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/imports/new': {
      id: '/_layout/imports/new'
      path: '/imports/new'
      fullPath: '/imports/new'
      preLoaderRoute: typeof LayoutImportsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/jobs/': {
      id: '/_layout/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof LayoutJobsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/jobs/$jobId': {
      id: '/_layout/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof LayoutJobsJobIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAuditRoute: typeof LayoutAuditRoute
  LayoutDirectoryRoute: typeof LayoutDirectoryRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutImportsImportIdRoute: typeof LayoutImportsImportIdRoute
  LayoutImportsNewRoute: typeof LayoutImportsNewRoute
  LayoutJobsJobIdRoute: typeof LayoutJobsJobIdRoute
  LayoutImportsIndexRoute: typeof LayoutImportsIndexRoute
  LayoutJobsIndexRoute: typeof LayoutJobsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAuditRoute: LayoutAuditRoute,
  LayoutDirectoryRoute: LayoutDirectoryRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutImportsImportIdRoute: LayoutImportsImportIdRoute,
  LayoutImportsNewRoute: LayoutImportsNewRoute,
  LayoutJobsJobIdRoute: LayoutJobsJobIdRoute,
  LayoutImportsIndexRoute: LayoutImportsIndexRoute,
  LayoutJobsIndexRoute: LayoutJobsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
